# Ez a kapcsoló mondja meg a Gradle-nek, hogy használja az AndroidX könyvtárakat
android.useAndroidX=true

# Ez a kapcsoló segít a régi könyvtárak automatikus átalakításában (biztonsági játék)
android.enableJetifier=true

# Optimalizálja a Gradle memóriahasználatát a buildelés során
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

